# Introduction to Numpy

In [5]:
import numpy as np

In [7]:
# create an array

hamoye = np.array([1,3,5,7,9,11])

In [8]:
hamoye

array([ 1,  3,  5,  7,  9, 11])

In [12]:
type(hamoye)

numpy.ndarray

 # Slice through arrays

In [16]:
hamoye[0:3]

array([1, 3, 5])

In [17]:
hamoye[3:]

array([ 7,  9, 11])

In [18]:
hamoye[2:4]

array([5, 7])

In [19]:
hamoye[3:5]

array([7, 9])

In [20]:
hamoye[4]

9

In [22]:
hamoye[4] = 26
hamoye

array([ 1,  3,  5,  7, 26, 11])

# 2D array

In [30]:
hamoye_2 = np.array([[1,3,5,7],[2,4,6,8]], float)

In [31]:
hamoye_2

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [32]:
hamoye_2[1,2]

6.0

In [33]:
hamoye_2[1,0]

2.0

In [35]:
hamoye_2[0,1]

3.0

In [40]:
hamoye_2[0:1]

array([[1., 3., 5., 7.]])

In [41]:
hamoye_2[0:2]

array([[1., 3., 5., 7.],
       [2., 4., 6., 8.]])

In [55]:
hamoye_2[:1]

array([[1., 3., 5., 7.]])

In [64]:
hamoye_2[: ,2]

array([5., 6.])

In [73]:
hamoye_2[-2:, -2:]

array([[5., 7.],
       [6., 8.]])

In [70]:
hamoye_2.dtype

dtype('float64')

In [71]:
len(hamoye_2)

2

## The "in" Statement for np arrays

In [74]:
23 in hamoye_2

False

In [75]:
8 in hamoye_2

True

In [76]:
hamoye_range = np.array(range(20), float) 

In [77]:
hamoye_range

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [79]:
hamoye_range = hamoye_range.reshape((5,4))

In [80]:
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [81]:
hamoye_range.shape

(5, 4)

In [82]:
a = np.array([1,2,3,4], float)

In [83]:
a.tolist()

[1.0, 2.0, 3.0, 4.0]

In [84]:
list(a)

[1.0, 2.0, 3.0, 4.0]

In [85]:
a.fill(0)

In [86]:
a

array([0., 0., 0., 0.])

In [87]:
hamoye_range.transpose

<function ndarray.transpose>

In [90]:
hamoye_range = np.array(range(20), float).reshape(5,4)

In [91]:
hamoye_range

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.]])

In [93]:
hamoye_range.transpose()

array([[ 0.,  4.,  8., 12., 16.],
       [ 1.,  5.,  9., 13., 17.],
       [ 2.,  6., 10., 14., 18.],
       [ 3.,  7., 11., 15., 19.]])

In [95]:
hamoye_range.flatten()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

# Array Concatenation

In [98]:
a = np.array([3,5,7])
b = np.array([1,11])
c = np.array([5,8,9])

np.concatenate((a,b,c))

array([ 3,  5,  7,  1, 11,  5,  8,  9])

In [99]:
x = np.array([[1,2,3],[4,7,9]])
y = np.array([[10,12,13], [14,17,19]])

np.concatenate((x,y))

array([[ 1,  2,  3],
       [ 4,  7,  9],
       [10, 12, 13],
       [14, 17, 19]])

In [100]:
np.concatenate((x,y), axis=1)

array([[ 1,  2,  3, 10, 12, 13],
       [ 4,  7,  9, 14, 17, 19]])

# Other creaive ways of creating an array

In [101]:
np.arange(20, dtype = float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [103]:
np.arange(0,20,3, dtype = float)

array([ 0.,  3.,  6.,  9., 12., 15., 18.])

In [104]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [106]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Special 2D arrays

In [107]:
np.identity(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [110]:
np.eye(5, k=-2, dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

# Array Mathematics

In [113]:
a = np.array([3,5,7])
b = np.array([1,11,13])
c = np.array([5,8,9])

In [114]:
a+b+c

array([ 9, 24, 29])

In [115]:
a*c

array([15, 40, 63])

In [116]:
a-c

array([-2, -3, -2])

In [117]:
a+b

array([ 4, 16, 20])

In [118]:
a*b

array([ 3, 55, 91])

In [119]:
b/c

array([0.2       , 1.375     , 1.44444444])

# Python-Numpy Broadcasting

In [121]:
a = np.array([[1,3],[0,5],[2,-1]], float)

In [126]:
b = np.array([1,11], float)

In [127]:
a + b

array([[ 2., 14.],
       [ 1., 16.],
       [ 3., 10.]])

In [129]:
b = np.array([[1,11],[1,11],[1,11]], float)
b

array([[ 1., 11.],
       [ 1., 11.],
       [ 1., 11.]])

# Floor, Ceil and Rint

Floor gives lower integer, ciel gives the higher integer & rint gives the nearest integer.

In [134]:
z = np.array([6.7, 2.3, 5.4, 1.192], float)
z

array([6.7  , 2.3  , 5.4  , 1.192])

In [135]:
np.floor(z)

array([6., 2., 5., 1.])

In [136]:
np.ceil(z)

array([7., 3., 6., 2.])

In [137]:
np.rint(z)

array([7., 2., 5., 1.])

In [138]:
np.e

2.718281828459045

In [139]:
np.pi

3.141592653589793

# Array Iteration

In [140]:
m = np.array([1,2,3,5,7,8], float)
m

array([1., 2., 3., 5., 7., 8.])

In [146]:
for hamoye in m:
    print(hamoye)

1.0
2.0
3.0
5.0
7.0
8.0


In [147]:
n = np.array([[1,3],[0,5],[2,-1]], float)

In [148]:
n

array([[ 1.,  3.],
       [ 0.,  5.],
       [ 2., -1.]])

In [150]:
for hamoye in n:
    print(hamoye)

[1. 3.]
[0. 5.]
[ 2. -1.]


In [151]:
for (a,b) in n:
    print(a*b)

3.0
0.0
-2.0
