In [10]:
#extent function
a = [1,2,3,4,5,6]
b = [13,21,34]

a.extend(b)
a

[1, 2, 3, 4, 5, 6, 13, 21, 34]

In [11]:
import numpy as np

In [12]:
#creating an identity matrix
f = np.eye(3)
print(f)

np.identity(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.array([1,0,0],[0,1,0],[0,0,1])

ValueError: only 2 non-keyword arguments accepted

In [14]:
#importing libraries needed to access dataset file

import pandas as pd
import numpy as np

In [15]:
#read the dataset

dt = pd.read_csv('fuel_ferc1.csv')
dt

record_id  utility_id_ferc1  report_year  \
0        f1_fuel_1994_12_1_0_7                 1         1994   
1       f1_fuel_1994_12_1_0_10                 1         1994   
2        f1_fuel_1994_12_2_0_1                 2         1994   
3        f1_fuel_1994_12_2_0_7                 2         1994   
4       f1_fuel_1994_12_2_0_10                 2         1994   
...                        ...               ...          ...   
29518  f1_fuel_2018_12_12_0_13                12         2018   
29519   f1_fuel_2018_12_12_1_1                12         2018   
29520  f1_fuel_2018_12_12_1_10                12         2018   
29521  f1_fuel_2018_12_12_1_13                12         2018   
29522  f1_fuel_2018_12_12_1_14                12         2018   

           plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0                  rockport                coal       ton        5377489.0   
1      rockport total plant                coal       ton       10486945.0   
2                    gorgas                coal       ton        2978683.0   
3                     barry                coal       ton        3739484.0   
4                 chickasaw                 gas       mcf          40533.0   
...                     ...                 ...       ...              ...   
29518    neil simpson ct #1                 gas       mcf          18799.0   
29519  cheyenne prairie 58%                 gas       mcf         806730.0   
29520     lange ct facility                 gas       mcf         104554.0   
29521       wygen 3 bhp 52%                coal       ton         315945.0   
29522       wygen 3 bhp 52%                 gas       mcf          17853.0   

       fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0                   16.590                      18.59   
1                   16.592                      18.58   
2                   24.130                      39.72   
3                   23.950                      47.21   
4                    1.000                       2.77   
...                    ...                        ...   
29518                1.059                       4.78   
29519                1.050                       3.65   
29520                1.060                       4.77   
29521               16.108                       3.06   
29522                1.059                       0.00   

       fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                             18.53                1.121  
1                             18.53                1.120  
2                             38.12                1.650  
3                             45.99                1.970  
4                              2.77                2.570  
...                             ...                  ...  
29518                          4.78                9.030  
29519                          3.65                6.950  
29520                          4.77                8.990  
29521                         14.76                1.110  
29522                          0.00               11.680  

[29523 rows x 11 columns]

In [16]:
#finding the standard deviation and 75th precentile of fuel mmbtu per unit 
dt.fuel_mmbtu_per_unit.describe().round(2)

count    29523.00
mean         8.49
std         10.60
min          0.00
25%          1.02
50%          5.76
75%         17.01
max        341.26
Name: fuel_mmbtu_per_unit, dtype: float64

In [17]:
#fuel type with the lowest average fuel cost per unit burned
dt.groupby('fuel_type_code_pudl').mean().round(2)

utility_id_ferc1  report_year  fuel_qty_burned  \
fuel_type_code_pudl                                                   
coal                           115.64      2004.62       1903472.81   
gas                            124.12      2005.98       4843182.72   
nuclear                        107.40      2002.97       5454838.43   
oil                            113.24      2007.20         63116.77   
other                          110.47      2001.70       2948136.61   
waste                          154.25      2005.65        117191.36   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
coal                               20.76                      67.42   
gas                                 1.02                      13.66   
nuclear                            17.58                    4955.16   
oil                                 5.81                     168.88   
other                               0.57                      18.25   
waste                               0.34                      19.52   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
coal                                       116.95                 1.79  
gas                                         12.10                 5.41  
nuclear                                  28616.92                 1.72  
oil                                        313.91                12.70  
other                                       16.87               155.08  
waste                                       18.41               822.71

In [18]:
#fuel type with the lowest average fuel cost per unit burned
dt.groupby('fuel_type_code_pudl').fuel_cost_per_unit_burned.mean()

fuel_type_code_pudl
coal         67.421830
gas          13.659397
nuclear    4955.157002
oil         168.877086
other        18.253856
waste        19.518122
Name: fuel_cost_per_unit_burned, dtype: float64

In [19]:
# year with the highest average fuel cost per unit delivered
highest_year = dt.groupby('report_year').fuel_cost_per_unit_delivered.mean()

highest_year.sort_values(ascending=False)

report_year
1997    11140.197239
1996     9196.705948
2000      985.362877
2009      652.694163
2018      499.269966
2015      326.535511
1998      287.154420
2014      192.737183
2013      172.307591
2004      139.524275
2016      103.901761
2010       91.862105
1994       63.636060
2012       60.994502
2001       60.050396
2011       59.774667
2008       58.588197
2003       55.663493
2002       47.594361
2017       46.196861
2007       43.325023
2005       41.438184
2006       38.657484
1995       32.735269
1999       25.551627
Name: fuel_cost_per_unit_delivered, dtype: float64

In [20]:
#skewness and kurtosis of fuel qty burned
skewness = round(dt.fuel_qty_burned.skew(), 2)
print(skewness)
kurtosiss= dt.fuel_qty_burned.kurt().round(2)
kurtosiss

15.85


651.37

In [21]:
#total number of missing values
print(dt.isnull().sum())

#percentage of missing values
dt.isnull().mean().round(4)*100

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64


record_id                       0.00
utility_id_ferc1                0.00
report_year                     0.00
plant_name_ferc1                0.00
fuel_type_code_pudl             0.00
fuel_unit                       0.61
fuel_qty_burned                 0.00
fuel_mmbtu_per_unit             0.00
fuel_cost_per_unit_burned       0.00
fuel_cost_per_unit_delivered    0.00
fuel_cost_per_mmbtu             0.00
dtype: float64

In [22]:
#correlation
dt.corr().round(2)

utility_id_ferc1  report_year  fuel_qty_burned  \
utility_id_ferc1                          1.00         0.09            -0.06   
report_year                               0.09         1.00             0.01   
fuel_qty_burned                          -0.06         0.01             1.00   
fuel_mmbtu_per_unit                      -0.07        -0.11            -0.08   
fuel_cost_per_unit_burned                -0.04         0.01            -0.02   
fuel_cost_per_unit_delivered             -0.02        -0.01            -0.00   
fuel_cost_per_mmbtu                       0.01         0.01            -0.00   

                              fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
utility_id_ferc1                            -0.07                      -0.04   
report_year                                 -0.11                       0.01   
fuel_qty_burned                             -0.08                      -0.02   
fuel_mmbtu_per_unit                          1.00                      -0.01   
fuel_cost_per_unit_burned                   -0.01                       1.00   
fuel_cost_per_unit_delivered                -0.01                       0.01   
fuel_cost_per_mmbtu                         -0.01                      -0.00   

                              fuel_cost_per_unit_delivered  \
utility_id_ferc1                                     -0.02   
report_year                                          -0.01   
fuel_qty_burned                                      -0.00   
fuel_mmbtu_per_unit                                  -0.01   
fuel_cost_per_unit_burned                             0.01   
fuel_cost_per_unit_delivered                          1.00   
fuel_cost_per_mmbtu                                  -0.00   

                              fuel_cost_per_mmbtu  
utility_id_ferc1                             0.01  
report_year                                  0.01  
fuel_qty_burned                             -0.00  
fuel_mmbtu_per_unit                         -0.01  
fuel_cost_per_unit_burned                   -0.00  
fuel_cost_per_unit_delivered                -0.00  
fuel_cost_per_mmbtu                          1.00